---
- name: mysql | Install MySQL Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: mysql | Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ database.root_pass }} login_user=root login_password={{ database.root_pass }}
  with_items:
    - "{{ hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: mysql | Create databases
  sudo: yes
  mysql_db: name={{ database.db }} state=present login_user=root login_password={{ database.root_pass }}
  with_items: mysql

- name: mysql | Create users
  sudo: yes
  mysql_user: name={{ database.user }} password={{ database.pass }} priv={{ database.db }}.*:ALL state=present login_user=root login_password={{ database.root_pass }}
  with_items: mysql
